version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  build:
    commands:
       - b="$(aws cloudformation describe-stacks --region ap-southeast-2 --stack-name seeds-website --query 'Stacks[*].Outputs[?OutputKey==`S3BucketName`].{CF:OutputValue}' --output text)" ; aws s3 sync www/ s3://$b

